catalog/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
	path('', views.index, name='index'),

	path('books/', views.BookListView.as_view(), name='books'),
	path('book/<int:pk>', views.BookDetailView.as_view(), name='book_detail'), # store primary key = pk

	path('authors/', views.AuthorListView.as_view(), name='authors'),
	path('authors/<int:pk>', views.AuthorDetailView.as_view(), name='author_detail'),

	path('mybooks/', views.LoanedBooksByUserListView.as_view(), name='my_borrowed'),
	path('allbooks/', views.AllLoanedBooksListView.as_view(), name='all_borrowed'),

	path('book/<uuid:pk>/renew/', views.renew_book_librarian, name='renew_book_librarian'),

	path('author/create/', views.AuthorCreate.as_view(), name='author_create'),
	path('author/<int:pk>/update/', views.AuthorUpdate.as_view(), name='author_update'),
	path('author/<int:pk>/delete/', views.AuthorDelete.as_view(), name='author_delete'),

	path('book/create/', views.BookCreate.as_view(), name='book_create'),
	path('book/<int:pk>/update/', views.BookUpdate.as_view(), name='book_update'),
	path('book/<int:pk>/delete/', views.BookDelete.as_view(), name='book_delete'),
]

liib1/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.views.generic import RedirectView

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
	path('', RedirectView.as_view(url='catalog/', permanent=True)),
    path('admin/', admin.site.urls),
	path('catalog/', include('catalog.urls')),
	path('accounts/', include('django.contrib.auth.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

catalog/models.py
from django.db import models

from django.urls import reverse # Use for get_absolute_url()
from django.conf import settings
from django.db.models import UniqueConstraint # Constrain fields to unique values
from django.db.models.functions import Lower # Return lower case value

import uuid
from datetime import date

# Create your models here.

class Genre(models.Model):
	"""Model representing a book genre."""

	# Fields

	name = models.CharField(
		max_length=200,
		unique=True,
		help_text="Enter a book genre (e.g., Science Fiction, French Poetry, etc.)"
	)

	def __str__(self):
		"""Strng for representing Model object."""
		return self.name
	
	def get_absolute_url(self):
		"""Returns the URL to access a particular genre instance."""
		return reverse('genre-detail', args=[str(self.id)])
	
	class Meta:
		constraints = [UniqueConstraint(
			Lower('name'),
			name='genre_name_case_insensitive_unique',
			violation_error_message="Genre already exists (case insensitive match)"
		)]

class Book(models.Model):
	"""Model representing a book (but not a specific copy of a book)."""

	# Fields

	title = models.CharField(max_length=200)
	# Book can only have one author, but authors can have multiple books
	# Author to be declared as a string as it hasn't been declared yet
	author = models.ForeignKey('Author', on_delete=models.RESTRICT, null=True)
	summary = models.TextField(max_length=1000, help_text='Enter a brief descrption of the book')
	isbn = models.CharField(
		'ISBN',
		max_length=13,
		unique=True,
		help_text='13 Character <a href="https://www.isbn-international.org/content/what-isbn">''">ISBN number</a>'
	)
	# Genre can contain many books, and books can cover many genres
	# Genre class has already been defined so we can specify object above
	genre = models.ManyToManyField(Genre, help_text="Select a genre for this book")
	language = models.ForeignKey('Language', on_delete=models.RESTRICT, null=True)

	def display_genre(self):
		"""Create a string for the Genre to display genre in Admin."""
		return ', '.join(genre.name for genre in self.genre.all()[:3])
	
	display_genre.short_description = 'Genre'

	def __str__(self):
		"""String for representing the Model object."""
		return self.title
	
	def get_absolute_url(self):
		'''Returns the URL to access a detail record for this book.'''
		return reverse('book_detail', args=[str(self.id)])
	
class BookInstance(models.Model):
	"""Model representing a specific copy of a book (that can be borrowed from the library)"""

	LOAN_STATUS = (
		('m', 'Maintenance'),
		('o', 'On loan'),
		('a', 'Available'),
		('r', 'Reserved')
	)

	# Fields

	id = models.UUIDField(
		primary_key=True,
		default=uuid.uuid4,
		help_text='Unique ID for this particular book across whole library'
	)
	book = models.ForeignKey('Book', on_delete=models.RESTRICT, null=True)
	imprint = models.CharField(max_length=200)
	due_back = models.DateField(null=True, blank=True)
	status = models.CharField(
		max_length=1,
		choices=LOAN_STATUS,
		blank=True,
		default='m',
		help_text='Book availability'
	)
	borrower = models.ForeignKey(
		settings.AUTH_USER_MODEL,
		on_delete=models.SET_NULL,
		null=True,
		blank=True
	)

	class Meta:
		ordering = ['due_back']
		permissions = (('can_mark_returned', 'Set book as returned'),)

	@property
	def is_overdue(self):
		"""Determines if the book is overdue based on the due date and the current date."""
		return bool(self.due_back and date.today() > self.due_back)
	
	def __str__(self):
		"""String for representing the Model object."""
		return f'${self.id} ({self.book.title})'
	
class Author(models.Model):
	"""Model representing an author."""

	# Fields
	first_name = models.CharField(max_length=100)
	last_name = models.CharField(max_length=100)
	date_of_birth = models.DateField(null=True, blank=True)
	date_of_death = models.DateField('Died', null=True, blank=True)

	class Meta:
		ordering = ['last_name', 'first_name']
	
	def get_absolute_url(self):
		"""Returns the URL to access a particular author instance."""
		return reverse('author_detail', args=[str(self.id)])
	
	def __str__(self):
		"""String for representing the Model object."""
		return f'{self.last_name}, {self.first_name}'
	
class Language(models.Model):
	"""Model representing a book's language."""

	# Fields
	
	name = models.CharField(max_length=100, help_text='Language of the book.', default='English')

	def __str__(self):
		return self.name
	
	def get_absolute_url(self):
		"""Returns the URL to access a particular language instance."""
		return reverse('language-detail', args=[str(self.id)])

catalog/forms.py
import datetime

from django import forms
from django.forms import ModelForm

from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _

from .models import BookInstance

class RenewBookForm(forms.Form):
	renewal_date = forms.DateField(help_text='Enter a date between now and 4 weeks (default 3).')

	def clean_renewal_date(self):
		data = self.cleaned_data['renewal_date']

		# Verify date is NOT in the past
		if data < datetime.date.today():
			raise ValidationError(_('Invalid date - renewal in past'))
		
		# Verify date is in the allowed range (over: >4 weeks from today)
		if data > datetime.date.today() + datetime.timedelta(weeks=4):
			raise ValidationError(_('Invalid date - renewal more than 4 weeks'))
		
		# *** Return cleaned data
		return data

class RenewBookModelForm(ModelForm):
	def clean_due_back(self):
		data = self.cleaned_data['due_back']

		# Verify date is NOT in the past
		if data < datetime.date.today():
			raise ValidationError(_('Invalid date - renewal in past'))
		
		# Verify date is in the allowed range (over: >4 weeks from today)
		if data > datetime.date.today() + datetime.timedelta(weeks=4):
			raise ValidationError(_('Invalid date - renewal more than 4 weeks'))

		return data

	class Meta:
		model = BookInstance
		fields = [ 'due_back' ]
		# mark the due_back field as the renewal date
		labels = { 'due_back' : _('New renewal date') }
		help_texts = { 'due_back' : _('Enter a date between now and 4 weeks (default 3).') }

catalog/views.py
from django.shortcuts import render, get_object_or_404
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView

from django.http import HttpResponseRedirect
from django.urls import reverse, reverse_lazy

from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin

import datetime

from .models import Book, BookInstance, Author, Genre
from catalog.forms import RenewBookForm

# Create your views here.

def index(request):
	'''View function for the home page of the site.'''

	# Object counts
	num_books = Book.objects.all().count()
	num_authors = Author.objects.count() # all implied
	num_instances = BookInstance.objects.all().count()

	# Available books, a=available
	num_instances_available = BookInstance.objects.filter(status__exact='a').count()

	num_genre_fantasy = Genre.objects.filter(name__iexact='fantasy').count()
	num_genre_drama = Genre.objects.filter(name__iexact='drana').count()

	num_book_topaz = Book.objects.filter(title__iexact='topaz').count()
	num_book_c = Book.objects.filter(title__iexact='sobre').count()

	# Number of visits in the view, counted via session variable
	num_visits = request.session.get('num_visits', 0)
	num_visits += 1
	request.session['num_visits'] = num_visits
	
	context = {
		'num_books' : num_books,
		'num_authors' : num_authors,
		'num_instances' : num_instances,
		'num_instances_available' : num_instances_available,

		'num_genre_fantasy' : num_genre_fantasy,
		'num_genre_drama' : num_genre_drama,

		'num_book_topaz' : num_book_topaz,
		'num_book_c' : num_book_c,

		'num_visits' : num_visits,
	}

	# render in template with data provided in context
	return render(request, 'index.html', context=context)

@login_required
@permission_required('catalog.can_mark_returned', raise_exception=True)
def renew_book_librarian(request, pk):
	# get object with primary key, return Http404 if it doesn't exist
	book_instance = get_object_or_404(BookInstance, pk=pk)

	# If POST request process form data
	if request.method == 'POST':
		# Create form instance and populate with data from request (binding)
		form = RenewBookForm(request.POST)

		if form.is_valid():
			# process the data in form.cleared_data as required (write to model due_back field)
			# ensure sanitization, validation, conversion to more 'friendly' data types
			book_instance.due_back = form.cleaned_data['renewal_date']
			book_instance.save()

			# redirect to success
			return HttpResponseRedirect(reverse('all_borrowed'))
		else:
			# doesn't work when producing renewal dates?
			context = {
				'form' : form,
				'book_instance' : book_instance,
			}

			return render(request, 'catalog/book_renew_librarian.html', context)
	
	# Produce default form for other methods like GET
	else:
		# default - 3 weeks
		proposed_renewal_date = datetime.date.today() + datetime.timedelta(weeks=3)
		form = RenewBookForm(initial={ 'renewal_date' : proposed_renewal_date })

		context = {
			'form' : form,
			'book_instance' : book_instance,
		}

		return render(request, 'catalog/book_renew_librarian.html', context)

# implementation II

# Book views

class BookListView(generic.ListView):
	model = Book

	context_object_name = 'book_list' # list name
	paginate_by = 10

	# def get_queryset(self):
	#	return Book.objects.filter(title__icontains='campana')[:5]

class BookDetailView(generic.DetailView):
	model = Book

# Author views

class AuthorListView(generic.ListView):
	model = Author

	context_object_name = 'author_list'
	paginate_by = 10

class AuthorDetailView(generic.DetailView):
	model = Author

class LoanedBooksByUserListView (LoginRequiredMixin, generic.ListView):
	"""Generic class-based view listing books on loan to the current user."""

	model = BookInstance
	template_name = 'catalog/bookinstance_list_borrowed_user.html'
	paginate_by = 10

	def get_queryset(self):
		return (
			BookInstance.objects
				.filter(borrower=self.request.user)
				.filter(status__exact='o')
				.order_by('due_back')
		)

class AllLoanedBooksListView(PermissionRequiredMixin, generic.ListView):
	'''Generic class-based view for lising all books on loan.'''

	permission_required = 'catalog.can_mark_returned'

	model = BookInstance
	template_name = 'catalog/bookinstance_list_all_borrowed.html'
	paginate_by = 10

	# get all books
	def get_queryset(self):
		return (
			BookInstance.objects
				.filter(status__exact='o')
				.order_by('due_back')
		)

# Author modification views

# create, update views utilize templates with '_form" suffix
class AuthorCreate(PermissionRequiredMixin, CreateView):
	model = Author
	fields = { 'first_name', 'last_name', 'date_of_birth', 'date_of_death' } # to be displayed
	initial = { 'date_of_death' : '11/11/2025' }
	permission_required = 'catalog.add_author'

class AuthorUpdate(PermissionRequiredMixin, UpdateView):
	model = Author
	fields = { 'first_name', 'last_name', 'date_of_birth', 'date_of_death' } # to be displayed
	permission_required = 'catalog.update_author'

# delete view utilizes templates with '_confirm_delete' suffix
class AuthorDelete(PermissionRequiredMixin, DeleteView):
	model = Author
	success_url = reverse_lazy('authors') # unknown if link exists
	permission_required = 'catalog.delete_author'

	def form_valid(self, form):
		try:
			self.object.delete()
			return HttpResponseRedirect(self.success_url)
		except Exception as e:
			return HttpResponseRedirect(reverse('author_delete'), kwargs={ 'pk' : self.object.pk })

# Book modification views

class BookCreate(PermissionRequiredMixin, CreateView):
	model = Book
	fields = { 'title', 'author', 'summary', 'isbn', 'genre' }
	permission_required = 'catalog.create_book'

class BookUpdate(PermissionRequiredMixin, UpdateView):
	model = Book
	fields = { 'title', 'author', 'summary', 'isbn', 'genre'}
	permission_required = 'catalog.update_book'

class BookDelete(PermissionRequiredMixin, DeleteView):
	model = Book
	success_url = reverse_lazy('books')
	permission_required = 'catalog.delete_book'

	def form_valid(self, form):
		try:
			self.object.delete()
			return HttpResponseRedirect(self.success_url)
		except Exception as e:
			return HttpResponseRedirect(reverse('book_delete'), kwargs={ 'pk' : self.object.pk })

catalog/templates/base_generic.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		{% block title %}
			<title>Document</title>
		{% endblock %}
		<link
			href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
			rel="stylesheet"
			integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
			crossorigin="anonymous"
		>
		{% load static %}
	</head>
	<body>
		<div class="container-fluid">
			<div class="row">
				<div class="col-sm-2">
					{% block sidebar %}
						<ul class="sidebar-nav">
							<li><a href="{% url 'index' %}">Home</a></li>
							<li><a href="{% url 'books' %}">All books</a></li>
							<li><a href="{% url 'authors' %}">All authors</a></li>

							{% if perms.catalog.can_mark_returned %}
								<li><a href="{% url 'all_borrowed' %}">All borrowed</a></li>
							{% endif %}

							{% if user.is_authenticated %}
								<li>User : {{ user.get_username }}</li>
								<li><a href="{% url 'my_borrowed' %}">My borrowed</a></li>
								<li> <!-- Log out -->
									<form id="logout-form" method="post" action="{% url 'logout' %}">
										{% csrf_token %}
										<!-- appear as link upon submission -->
										<button type="submit" class="btn btn-link">LOGOUT</button>
									</form>
								</li>
							{% else %}
								<li><a href="{% url 'login' %}?next={{ request.path }}">Login</a></li>
							{% endif %}

							<li>Staff</li>
							<li><a href="{% url 'all_borrowed' %}">All borrowed</a></li>

							{% if perms.catalog.add_author %}
								<li><a href="{% url 'author_create' %}">Create author</a></li>
							{% endif %}

							{% if perms.catalog.add_book %}
								<li><a href="{% url 'book_create' %}">Create book</a></li>
							{% endif %}
						</ul>
					{% endblock %}
				</div>
				<div class="col-sm-10">
					{% block content %}{% endblock %}

					{% block pagination %}
						{% if is_paginated %}
							<div class="pagination">
								<span class="page-links">
									{% if page_obj.has_previous %}
										<a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">
											Previous
										</a>
									{% endif %}

									<span class="page-current">
										Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
									</span>

									{% if page_obj.has_next %}
										<a href="{{ request.path }}?page={{ page_obj.next_page_number}}">
											Next
										</a>
									{% endif %}
								</span>
							</div>
						{% endif %}
					{% endblock %}
				</div>
			</div>
		</div>
	</body>
</html>

catalog/templates/index.html
{% extends "base_generic.html" %}

{% block title %}
	<title>Local Library</title>
{% endblock %}

{% block content %}
	<h1>Local library home</h1>
	<p>Welcome to LocalLibrary, a website developed by <em>Mozilla Developer Network</em></p>
	<h2>Dynamic content</h2>
	<p>The library has the following record counts:</p>
	<ul>
		<li><strong>Books:</strong> {{ num_books }}</li>
		<li><strong>Copies:</strong> {{ num_instances }}</li>
		<li><strong>Copies available:</strong> {{ num_copies_available }}</li>
		<li><strong>Authors:</strong> {{ num_authors }}</li>
	</ul>
	<p>You have visited this page {{ num_visits }} time{{ num_visits|pluralize }}</p>
	<p>The following genres are present:</p>
	<ul>
		<li><strong>Fantasy:</strong> {{ num_genre_fantasy }}</li>
		<li><strong>Drama:</strong> {{ num_genre_drama }}</li>
	</ul>
	<p>The following books are present:</p>
	<ul>
		<li><strong>TOPAZ:</strong> {{ num_book_topaz }}</li>
		<li><strong>Campana sobre campana:</strong> {{ num_book_c }}</li>
	</ul>
{% endblock %}